config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"                              # Topページを設定
  devise_for :users
  get "/home/about" => "homes#about", as: "about"   # aboutをルートに追加

  get "search" => "searches#search" #検索

  resources :books, only: [:new, :index,:show,:edit,:create,:destroy,:update] do
    # いいね機能のルーティングを設定
    resource :favorites, only: [:create, :destroy]
    # コメント機能のルーティングを設定
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- フッター設定 -->
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <!-- Bookersのリンク -->
      <%= link_to "Bookers", root_path, class: "navbar-brand" %>

      <!-- ナビゲーションバー -->
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <!-- ログイン状態の場合 -->
          <% if user_signed_in? %>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <!-- Homeのリンク -->
              <li class="nav-item text-light">
                <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>
                    <span>Home</span>
                <% end %>
              </li>

              <!-- Usersのリンク -->
              <li class="nav-item text-light">
                <%=  link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i>
                  <span>Users</span>
                <% end %>
              </li>

              <!-- Booksのリンク -->
              <li class="nav-item text-ligh">
                <%=  link_to books_path , class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i>
                  <span>Books</span>
                <% end %>
              </li>

              <!-- Log outのリンク -->
              <li class="nav-item text-light">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i>
                  <span>Log out</span>
                <% end %>
              </li>
            </div>

          <!-- ログイン前の状態の場合 -->
          <% else %>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <!-- Homeのリンク -->
              <li class="nav-item text-light">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>
                  <span>Home</span>
                <% end %>
              </li>

              <!-- Aboutのリンク -->
              <li class="nav-item text-light">
                <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i>
                  <span>About</span>
                <% end %>
              </li>

              <!-- Sign upのリンク -->
              <li class="nav-item text-light">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i>
                  <span>Sign up</span>
                <% end %>
              </li>

              <!-- Log inのリンク -->
              <li class="nav-item text-light">
                <%= link_to new_user_session_path , class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i>
                  <span>Log in</span>
                <% end %>
              </li>
            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- FontAwesomeの導入、～fontawesome.com/の後ろは自身のKitCodeのIDが入ります  -->
    <script src="https://kit.fontawesome.com/3643740517.js" crossorigin="anonymous"></script>

    <!-- stylesheet_pack_tagの場合は、app/javascript 配下のファイルを参照する -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値] -->
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <div class="d-flex justify-content-center mb-2">
          <%= render "searches/search" %> <!-- 検索 -->
        </div>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>